jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set JDK
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build without Scala
      run: ./gradlew build --scan --stacktrace -Porg.gradle.project.enable_scala=false
    - continue-on-error: true
      name: Build with Scala
      run: ./gradlew build --scan --stacktrace -Porg.gradle.project.enable_scala=true
    strategy:
      matrix:
        java:
        - 8
        - 11
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
